### PR TITLE
Fix/small fixes

### LINKED ISSUE #255: [Backend] Retrieve cumulative details for claims
We need to get cumulative details for each claim as we did for redeem rewards.

### PR DESCRIPTION
**Pull request by Malak67**
# Generic Pull Request template

## Linked issue

Please link the issue:

ex. Closes #255 #254 #253 #251 #252 .

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.
- [ ] The changes impact front-end.

## For changes impacting frontend

Please leave some screenshots/video recordings of the newly implemented interface and the Figma link for its initial design.

### Screenshots/ recordings

=> Multimedia here.

### Figma link

=> Figma link here.

## Description

Please provide a short description about what the PR contains.

## Funny gif

Leave a funny gif for faster review.

### CODE REVIEW

File: services/client/src/hooks/useContractEscrowClaim.tsx [hunk 1]
```diff
@@ -23,6 +23,7 @@ export const useContractEscrowClaim = (
 ) => {
   const { abi } = ABIs.contracts.DynamicEscrow;
   const [isWrite, setIsWrite] = useState<boolean>(false);
+  const [shouldWrite, setShouldWrite] = useState<boolean>(false);
```
Comment (rattrap) [inline services/client/src/hooks/useContractEscrowClaim.tsx:26]: This whole isWrite, shouldWrite thing is really confusing.

File: services/client/src/models/Redeem.model.ts [hunk 2]
```diff
@@ -31,6 +31,7 @@ export interface HypeReward {
   claimed: boolean;
   poolName?: string;
   pool: HypePool;
+  impressions?: RewardsDetails[];
```
Comment (rattrap) [inline services/client/src/models/Redeem.model.ts:34]: Are these rewards or impressions?

File: services/client/src/utils/prettifyNumber.ts [hunk 3]
```diff
@@ -1,25 +1,41 @@
+function removeTrailingZeros(numStr: string): string {
+  return numStr.indexOf('.') !== -1 && numStr.split('.')[1] === '00'
+    ? numStr.split('.')[0]
+    : numStr;
+}
```
Comment (rattrap) [inline services/client/src/utils/prettifyNumber.ts:5]: This whole thing can be replaced with `parseFloat(numStr).toString()`

File: services/hype-backend/src/modules/reward/reward.service.ts [hunk 4]
```diff
@@ -112,49 +112,61 @@ export class RewardService {
...
+        .addSelect('SUM(CAST(reward.amount AS DECIMAL))::TEXT', 'totalRewards')
+        .where('reward.claimId = :claimId', { claimId })
+        .groupBy('reward.telegramGroup, reward.poolId')
+        .getRawMany();
+
+      return rewards.map((reward) => ({
+        telegramGroup: reward.telegram_group,
+        impressions: reward.totalImpressions,
+        rewards: reward.totalRewards,
+      }));
```
Comment (rattrap) [inline services/hype-backend/src/modules/reward/reward.service.ts:141]: If we rename the fields in the query, we don't need this map anymore.

File: services/hype-backend/src/modules/reward/reward.service.ts [hunk 5]
```diff
@@ -112,49 +112,61 @@ export class RewardService {
...
+      .createQueryBuilder('claim')
+      .where('LOWER(claim.rewardee) = LOWER(:address)', { address })
+      .andWhere('claim.claimed = :claimed', { claimed: false })
+      .getMany();
+
+    const rewardClaims = await this.claimRepository
+      .createQueryBuilder('claim')
+      .where('LOWER(claim.rewardee) = LOWER(:address)', { address })
+      .andWhere('claim.claimed = :claimed', { claimed: true })
+      .getMany();
```
Comment (rattrap) [inline services/hype-backend/src/modules/reward/reward.service.ts:125]: Let's rename these with more relevant names like `rewards`, `unClaimedClaims`, `claimedClaims`

**Review by rattrap — CHANGES_REQUESTED** [review]

File: services/client/src/hooks/useContractEscrowClaim.tsx (hunk 1 above)
Comment (Malak67) [reply services/client/src/hooks/useContractEscrowClaim.tsx:26]: This will be handled in a new PR, probably replacing wagmi completely from write and read to contracts.

**Review by rattrap — APPROVED** [review]
